### ISSUE TITLE
Q&A

### ISSUE THREAD

**Issue by FrankFeenix** [ClaudiuHKS/CSGO-Servers#1]
How to run this project under C++? Thanks

**Comment by ClaudiuHKS** [comment]
Windows or linux?

**Comment by FrankFeenix** [comment]
Windows

**Comment by ClaudiuHKS** [comment]
1. Install [Microsoft Visual Studio Community 2019](https://visualstudio.microsoft.com/) or [direct link](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16).
2. Do what you see in this [picture](https://user-images.githubusercontent.com/9334579/115960024-d4ec0300-a517-11eb-81ee-1b276a401d0d.png).
3. Download [hl2sdk-csgo](https://github.com/alliedmodders/hl2sdk/tree/csgo) or [direct link](https://github.com/alliedmodders/hl2sdk/archive/refs/heads/csgo.zip).
4. Download [metamod-source-master](https://github.com/alliedmodders/metamod-source) or [direct link](https://github.com/alliedmodders/metamod-source/archive/refs/heads/master.zip).
5. Unzip the zipped files to your local drive. Do not change the folder names. The folder locations must the be same as shown [here](https://user-images.githubusercontent.com/9334579/115960024-d4ec0300-a517-11eb-81ee-1b276a401d0d.png).
6. Double click the **.sln** file.
7. Select [Release - Original](https://user-images.githubusercontent.com/9334579/115960249-f13c6f80-a518-11eb-95b5-06e35dae0de9.png).
8. Under **Release - Original** click then [Configuration Manager...](https://user-images.githubusercontent.com/9334579/115960334-73c52f00-a519-11eb-933e-f4ad1017c82c.png) to make sure you build for [Release - CS GO](https://user-images.githubusercontent.com/9334579/115960288-2d6fd000-a519-11eb-9d5e-b6a9ddf63fe2.png).
9. Into the **Solution Explorer** right click on **stub_mm** and select **Build** or **Rebuild**.

**Comment by ClaudiuHKS** [comment]
The resulted **.dll** file will then need [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) or [direct link](https://aka.ms/vs/16/release/vc_redist.x86.exe).
If it will fail to load, missing **Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019** on that system, is the problem.

**Comment by ClaudiuHKS** [comment]
**libtier0.so** & **libvstdlib.so** are copied from `hl2sdk-csgo\lib\linux`. They are only for Linux, anways, just saying.

**Comment by FrankFeenix** [comment]
thx
